package com.fanniemae.mcasrest.domain;


import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Master {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	private String unid;
	private String lender_name;
	private String lender_number;
	private String m_region;
	private String m_requestor;
	private String m_neg_date;
	private String m_estvolume;
	private String m_con_mandatory;
	private String m_backup;
	private String m_con_optional;
	private String m_tolerance;
	private String m_LenderPaidMI;
	private String m_Evergreen;
	private String evergreen_yr;
	private String m_RBPYesNo;
	private String alnce;
	private String cmb;
	private String streamline;
	private String m_kind;
	private String m_l_title;
	private String m_L_Phone;
	private String m_L_FAX;
	private String m_L_lastname;
	private String m_L_ZIP;
	private String m_L_prefix;
	private String m_L_Addr1;
	private String m_L_Addr2;
	private String m_L_City;
	private String Newaffifld;
	private String m_L_State;
	private String Email;
	private String CSU_SentLegal;
	private String CSU_ReturnLegal;
	private String CSU_ContractMailed;
	private String CSU_RejLender;
	private String CSU_SignedLender;
	private String CSU_ReturnedLender;
	private String CSU_ContractCanceled;
	private String team_codes;
	private String DocAuthors;
	private String m_Negotiator;
	private String m_Mandatory;
	private String m_Optional;
	private String m_Total;
	private String m_EffDate;
	private String m_conversionamount;
	private String m_Commit;
	private String m_ExpDate;
	private String m_EffDateOrig;
	private String m_ConTotal;
	private int amendmentnum;
	private String m_ClosedPools;
	private String m_CashOutstanding;
	private String m_MasterBalance;
	private String m_PairOffs;
	private String m_CashPurchased;
	private String AStartDate;
	private String AEndDate;
	private String udateon;
	private String cudateon;
	private String Seq;
	private String m_ConvAmt;
	private String m_ConvStartDate;
	private String m_ConvEndDate;
	private String m_ConvTerm;
	private String m_TotalConvAmt;
	private String m_L_Status;
	private String m_Affiliates;
	private String NewLendnames;
	private String Status;
	private String CS_Req_SentLegal;
	private String CS_Upd_SentLegal;
	private String CS_Req_ReturnLegal;
	private String CS_Upd_ReturnLegal;
	private String CS_Req_ContractMailed;
	private String CS_Upd_ContractMailed;
	private String CS_Req_RejLender;
	private String CS_Upd_RejLender;
	private String CS_Req_SignedLender;
	private String CS_Upd_SignedLender;
	private String CS_Req_ReturnedLender;
	private String CS_Upd_ReturnedLender;
	private String CS_Req_ContractCanceled;
	private String CS_Upd_ContractCanceled;
	private String LastUnlcked;
	private String Unlckedby;
	private String UnlckedReason;
	private String UnlckedStatus;
	private String V_DecisionMaker;
	private String Author;
	private String CreationDate;
	private String Editor;
	private String Moddate;
	private String m_Type;

}
